version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    - /var/log:/host_logs
    depends_on:
      - Elasticsearch
    ports:
      - '5044:5044'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m" 

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://10.15.1.236:9200
    depends_on:
      - Elasticsearch

volumes:
  elastic_data: {}


